name: UI Simple Tests

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      tagsInclude:
        description: "Tags to include (comma-separated)"
        required: false
        default: "Regression"
      tagsExclude:
        description: "Tags to exclude (comma-separated)"
        required: false
        default: "Flaky"
jobs:
  run:
    uses: CyborgCodeSyndicate/roa-github-workflows/.github/workflows/roa-tests.yml@v1.0.0-rc-1
    with:
      kind: ui
      project_module: ui-simple-test-framework
      tags_include: ${{ github.event.inputs.tagsInclude }}
      tags_exclude: ${{ github.event.inputs.tagsExclude }}
      grid_node_max_sessions: 3
    secrets:
      maven_user:  ${{ secrets.GH_PACKAGES_USER }}
      maven_token: ${{ secrets.GH_PACKAGES_PAT }}
